### ISSUE TITLE
Incur Error

### ISSUE THREAD

**Issue by guanhuankang** [Andrew-Qibin/dss_crf#2]
I try to install it on OS win10(64bits), but I fail to run command "python setup.py install". Before installation, I install Cython with command "conda install Cython" as it required. If you have fixed this error, could you sent me a msg? Thanks!

**Comment by tamireiny** [comment]
@Andrew-Qibin I run setup.py install using Pycharm, OS: Windows 10, 64 bits. 
And I get the following error, any suggestion how to solve? Thanks

Connected to pydev debugger (build 193.6911.25)
running install
running build
running build_py
running build_ext
warning: build_py: byte-compiling is disabled, skipping.

building 'pydensecrf.eigen' extension
C:\Users\Tamir\anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ipydensecrf/densecrf/include -Ipydensecrf -IC:\Users\Tamir\anaconda3\include -IC:\Users\Tamir\anaconda3\include -c pydensecrf/eigen.cpp -o build\temp.win-amd64-3.7\Release\pydensecrf\eigen.o
In file included from pydensecrf/densecrf/include/Eigen/Core:248:0,
                 from pydensecrf/densecrf/include/Eigen/Dense:1,
                 from pydensecrf/eigen.cpp:266:
pydensecrf/densecrf/include/Eigen/src/Core/util/Memory.h: In function 'Index Eigen::internal::first_aligned(const Scalar*, Index)':
pydensecrf/densecrf/include/Eigen/src/Core/util/Memory.h:454:48: warning: typedef 'Packet' locally defined but not used [-Wunused-local-typedefs]
   typedef typename packet_traits<Scalar>::type Packet;
                                                ^
In file included from pydensecrf/densecrf/include/Eigen/Core:324:0,
                 from pydensecrf/densecrf/include/Eigen/Dense:1,
                 from pydensecrf/eigen.cpp:266:
pydensecrf/densecrf/include/Eigen/src/Core/products/SelfadjointMatrixVector.h: In static member function 'static void Eigen::internal::selfadjoint_matrix_vector_product<Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, Version>::run(Index, const Scalar*, Index, const Scalar*, Index, Scalar*, Scalar)':
pydensecrf/densecrf/include/Eigen/src/Core/products/SelfadjointMatrixVector.h:38:44: warning: typedef 'RealScalar' locally defined but not used [-Wunused-local-typedefs]
   typedef typename NumTraits<Scalar>::Real RealScalar;
                                            ^
In file included from pydensecrf/densecrf/include/Eigen/QR:26:0,
                 from pydensecrf/densecrf/include/Eigen/Dense:4,
                 from pydensecrf/eigen.cpp:266:
pydensecrf/densecrf/include/Eigen/src/QR/HouseholderQR.h: In function 'void Eigen::internal::householder_qr_inplace_blocked(MatrixQR&, HCoeffs&, typename MatrixQR::Index, typename MatrixQR::Scalar*)':
pydensecrf/densecrf/include/Eigen/src/QR/HouseholderQR.h:235:41: warning: typedef 'RealScalar' locally defined but not used [-Wunused-local-typedefs]
   typedef typename MatrixQR::RealScalar RealScalar;
                                         ^
In file included from pydensecrf/densecrf/include/Eigen/Eigenvalues:28:0,
                 from pydensecrf/densecrf/include/Eigen/Dense:7,
                 from pydensecrf/eigen.cpp:266:
pydensecrf/densecrf/include/Eigen/src/Eigenvalues/Tridiagonalization.h: In function 'void Eigen::internal::tridiagonalization_inplace(MatrixType&, DiagonalType&, SubDiagonalType&, bool)':
pydensecrf/densecrf/include/Eigen/src/Eigenvalues/Tridiagonalization.h:428:38: warning: typedef 'Index' locally defined but not used [-Wunused-local-typedefs]
   typedef typename MatrixType::Index Index;
                                      ^
In file included from pydensecrf/densecrf/include/Eigen/Eigenvalues:34:0,
                 from pydensecrf/densecrf/include/Eigen/Dense:7,
                 from pydensecrf/eigen.cpp:266:
pydensecrf/densecrf/include/Eigen/src/Eigenvalues/ComplexSchur.h: In static member function 'static void Eigen::internal::complex_schur_reduce_to_hessenberg<MatrixType, false>::run(Eigen::ComplexSchur<MatrixType>&, const MatrixType&, bool)':
pydensecrf/densecrf/include/Eigen/src/Eigenvalues/ComplexSchur.h:312:66: warning: typedef 'ComplexMatrixType' locally defined but not used [-Wunused-local-typedefs]
     typedef typename ComplexSchur<MatrixType>::ComplexMatrixType ComplexMatrixType;
                                                                  ^
pydensecrf/eigen.cpp: In function 'void __Pyx_ExceptionSave(PyObject**, PyObject**, PyObject**)':
pydensecrf/eigen.cpp:16787:21: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_type'
     *type = tstate->exc_type;
                     ^
pydensecrf/eigen.cpp:16788:22: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_value'
     *value = tstate->exc_value;
                      ^
pydensecrf/eigen.cpp:16789:19: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_traceback'
     *tb = tstate->exc_traceback;
                   ^
pydensecrf/eigen.cpp: In function 'void __Pyx_ExceptionReset(PyObject*, PyObject*, PyObject*)':
pydensecrf/eigen.cpp:16801:24: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_type'
     tmp_type = tstate->exc_type;
                        ^
pydensecrf/eigen.cpp:16802:25: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_value'
     tmp_value = tstate->exc_value;
                         ^
pydensecrf/eigen.cpp:16803:22: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_traceback'
     tmp_tb = tstate->exc_traceback;
                      ^
pydensecrf/eigen.cpp:16804:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_type'
     tstate->exc_type = type;
             ^
pydensecrf/eigen.cpp:16805:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_value'
     tstate->exc_value = value;
             ^
pydensecrf/eigen.cpp:16806:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_traceback'
     tstate->exc_traceback = tb;
             ^
pydensecrf/eigen.cpp: In function 'int __Pyx_GetException(PyObject**, PyObject**, PyObject**)':
pydensecrf/eigen.cpp:16849:24: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_type'
     tmp_type = tstate->exc_type;
                        ^
pydensecrf/eigen.cpp:16850:25: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_value'
     tmp_value = tstate->exc_value;
                         ^
pydensecrf/eigen.cpp:16851:22: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_traceback'
     tmp_tb = tstate->exc_traceback;
                      ^
pydensecrf/eigen.cpp:16852:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_type'
     tstate->exc_type = local_type;
             ^
pydensecrf/eigen.cpp:16853:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_value'
     tstate->exc_value = local_value;
             ^
pydensecrf/eigen.cpp:16854:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_traceback'
     tstate->exc_traceback = local_tb;
             ^
pydensecrf/eigen.cpp: In function 'void __Pyx_ExceptionSwap(PyObject**, PyObject**, PyObject**)':
pydensecrf/eigen.cpp:16876:24: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_type'
     tmp_type = tstate->exc_type;
                        ^
pydensecrf/eigen.cpp:16877:25: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_value'
     tmp_value = tstate->exc_value;
                         ^
pydensecrf/eigen.cpp:16878:22: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_traceback'
     tmp_tb = tstate->exc_traceback;
                      ^
pydensecrf/eigen.cpp:16879:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_type'
     tstate->exc_type = *type;
             ^
pydensecrf/eigen.cpp:16880:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_value'
     tstate->exc_value = *value;
             ^
pydensecrf/eigen.cpp:16881:13: error: 'PyThreadState {aka struct _ts}' has no member named 'exc_traceback'
     tstate->exc_traceback = *tb;
             ^
In file included from pydensecrf/eigen.cpp:267:0:
pydensecrf/eigen_impl.cpp: At global scope:
pydensecrf/eigen_impl.cpp:13:13: warning: 'void vecf2buf(const VectorXf&, float*)' defined but not used [-Wunused-function]
 static void vecf2buf(const Eigen::VectorXf& vec, float *mem)
             ^
pydensecrf/eigen_impl.cpp:27:13: warning: 'void matf2buf(const MatrixXf&, float*)' defined but not used [-Wunused-function]
 static void matf2buf(const Eigen::MatrixXf& mat, float *mem)
             ^
error: command 'C:\\Users\\Tamir\\anaconda3\\Library\\mingw-w64\\bin\\gcc.exe' failed with exit status 1

**Comment by guanhuankang** [comment]
You could have a try on this https://github.com/lucasb-eyer/pydensecrf Also, you could download the .whl file and install by running “pip install whl file name”. Hope this could help you! Thanks.

**Comment by tamireiny** [comment]
@guanhuankang Thanks for the fast reply. I could not find the .whl file you mentioned, can you please give me direct link to this file?

**Comment by guanhuankang** [comment]
You could download the corresponding whl files from this link (I recommend you search pydensecrf on this page to locate the target file) https://www.lfd.uci.edu/~gohlke/pythonlibs/ . Plus, you could try to run pip install pydensecrf .

**Comment by tamireiny** [comment]
@guanhuankang When I install via pip I get ModuleNotFoundError: No module named 'pydensecrf'
When I try to install pip install pydensecrf-1.0rc2-cp39-cp39-win_amd64.whl, I get: 
ERROR: pydensecrf-1.0rc2-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.
Any idea what to do?

**Comment by guanhuankang** [comment]
Sorry, I have no idea about the issues you encountered in. Make sure you have downloaded the correct whl file. I.e. pydensecrf-1.0rc2-cp39-cp39-win_amd64.whl should be installed on windows platform with a python 3.9, I guess.
